"""Application contract for replaceable memory providers, independent of Graphiti.

The SQLite implementation (brain_store.BrainStore) is the only installed backend and
nothing imports this Protocol at run time; it documents what a replacement must
provide. Future graph adapters must retain scopes, current-source validation,
forgetting and capacity semantics, and keep this signature in step with BrainStore.
"""
from typing import Protocol


class MemoryBackend(Protocol):
    def propose(self, payload: dict) -> dict: ...
    def approve(self, memory_id: str, reviewer: str, note: str) -> dict: ...
    def search(self, query: str, project_id: str, user_id: str='local',
               limit: int | None=None, max_chars: int | None=None, hops: int | None=None, *,
               strategy: str='auto', record_trace: bool=True, profile: str='general',
               depth: str='compact', jev: bool=True) -> dict: ...
    def forget(self, memory_id: str, actor: str, reason: str) -> dict: ...
    def supersede(self, old_id: str, new_id: str, actor: str, reason: str) -> dict: ...
    def export(self, project_id: str, user_id: str='local') -> dict: ...
    def changes(self, project_id: str, user_id: str='local', after: int=0, limit: int=100) -> dict: ...
