"""Application contract for replaceable memory providers, independent of Graphiti.

The SQLite implementation is the only installed backend. Future graph adapters
must retain scopes, current-source validation, forgetting and capacity semantics.
"""
from typing import Protocol


class MemoryBackend(Protocol):
    def propose(self, payload: dict) -> dict: ...
    def approve(self, memory_id: str, reviewer: str, note: str) -> dict: ...
    def search(self, query: str, project_id: str, user_id: str='local',
               limit: int=6, max_chars: int=8000, hops: int=1) -> dict: ...
    def forget(self, memory_id: str, actor: str, reason: str) -> dict: ...
    def supersede(self, old_id: str, new_id: str, actor: str, reason: str) -> dict: ...
    def export(self, project_id: str, user_id: str='local') -> dict: ...
    def changes(self, project_id: str, user_id: str='local', after: int=0, limit: int=100) -> dict: ...
