"""Read Codex subscription limits through the installed official app-server.

Only initialize, initialized, and account/rateLimits/read are sent. No model
thread, inference, login, credit redemption, or account modification is requested.
Raw server output is never printed or saved because it can contain account IDs.
The protocol was verified against the schemas generated by Codex 0.153.0.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import math
from pathlib import Path
import queue
import shutil
import subprocess
import sys
import tempfile
import threading
import time

SOURCE = "official Codex app-server account/rateLimits/read"


class QuotaError(RuntimeError):
    """Only fixed, non-sensitive messages may be included in this exception."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def timestamp(value: object) -> str | None:
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise QuotaError("Codex returned an invalid quota reset timestamp.")
    try:
        return datetime.fromtimestamp(value, timezone.utc).isoformat().replace("+00:00", "Z")
    except (ValueError, OSError, OverflowError):
        raise QuotaError("Codex returned an invalid quota reset timestamp.") from None


def percentage(value: object) -> float:
    if isinstance(value, bool) or not isinstance(value, (float, int)):
        raise QuotaError("Codex returned a missing or invalid quota percentage.")
    if not math.isfinite(value) or value < 0:
        raise QuotaError("Codex returned an invalid quota percentage.")
    return float(value)


def parse_rate_limits(result: object, observed_at: str | None = None) -> dict:
    """Normalize all returned meters; never treat missing quota as available.

    A newer multi-bucket view replaces its backward-compatible single-bucket
    mirror. Credit balances/reset credits never supplement included allowance.
    Unfamiliar bucket identifiers are hashed rather than exposed as display text.
    """
    if not isinstance(result, dict):
        raise QuotaError("Codex returned an invalid quota response.")
    multi = result.get("rateLimitsByLimitId")
    if multi is not None and not isinstance(multi, dict):
        raise QuotaError("Codex returned an invalid multi-bucket quota response.")
    if multi:
        buckets = list(multi.items())
    elif isinstance(result.get("rateLimits"), dict) and result["rateLimits"]:
        buckets = [("codex", result["rateLimits"])]
    else:
        raise QuotaError("Codex did not report a usable subscription quota.")
    observed = observed_at or utc_now()
    windows = []
    seen = set()
    for bucket_id, bucket in buckets:
        if not isinstance(bucket_id, str) or not isinstance(bucket, dict):
            raise QuotaError("Codex returned an invalid quota bucket.")
        known_bucket_fields = {"credits", "individualLimit", "limitId", "limitName",
            "planType", "primary", "secondary", "rateLimitReachedType", "spendControlReached"}
        if set(bucket) - known_bucket_fields:
            raise QuotaError("Codex quota schema changed; revalidate all applicable limits.")
        prefix = "codex" if bucket_id == "codex" else (
            "codex-bucket-" + hashlib.sha256(bucket_id.encode()).hexdigest()[:12]
        )
        bucket_windows = []

        def append(suffix: str, remaining: float, reset: object = None) -> None:
            identity = prefix + "-" + suffix
            if identity in seen:
                raise QuotaError("Codex returned ambiguous quota windows.")
            seen.add(identity)
            bucket_windows.append({
                "id": identity, "remaining_pct": min(100, max(0, remaining)),
                "observed_at": observed, "reset_at": timestamp(reset),
                "max_age_seconds": 600, "source": SOURCE,
            })

        for slot in ("primary", "secondary"):
            window = bucket.get(slot)
            if window is None:
                continue
            if not isinstance(window, dict):
                raise QuotaError("Codex returned an invalid quota window.")
            if set(window) - {"usedPercent", "windowDurationMins", "resetsAt"}:
                raise QuotaError("Codex quota window schema changed; revalidate the adapter.")
            used = percentage(window.get("usedPercent"))
            duration = window.get("windowDurationMins")
            if duration is not None and (isinstance(duration, bool) or
                    not isinstance(duration, int) or duration <= 0):
                raise QuotaError("Codex returned an invalid quota duration.")
            suffix = {300: "five-hour", 10080: "weekly"}.get(duration, slot)
            append(suffix, 100 - used, window.get("resetsAt"))
        individual = bucket.get("individualLimit")
        if individual is not None:
            if not isinstance(individual, dict):
                raise QuotaError("Codex returned invalid individual spend-control data.")
            remaining = percentage(individual.get("remainingPercent"))
            if remaining > 100:
                raise QuotaError("Codex returned invalid individual spend-control data.")
            append("individual-spend-control", remaining, individual.get("resetsAt"))
        reached = bucket.get("spendControlReached")
        if reached is not None and not isinstance(reached, bool):
            raise QuotaError("Codex returned invalid spend-control state.")
        reason = bucket.get("rateLimitReachedType")
        if reason is not None and not isinstance(reason, str):
            raise QuotaError("Codex returned invalid rate-limit state.")
        if reached or reason:
            # Any explicit denial, including a newly added reason, closes the gate.
            append("provider-block", 0)
        elif not bucket_windows:
            raise QuotaError("A Codex quota bucket has no usable allowance data.")
        else:
            # Keep this sentinel present in healthy responses so a fresh success
            # explicitly clears an earlier denial in the guard's required pools.
            # This is an admission flag, not extra included quota or credits.
            append("provider-block", 100)
        windows.extend(bucket_windows)
    return {"provider": "codex", "status": "ok", "observed_at": observed,
            "no_model_calls": True, "windows": windows}


def find_codex() -> str:
    candidate = shutil.which("codex.exe") or shutil.which("codex")
    if candidate:
        return candidate
    extensions = Path.home() / ".vscode" / "extensions"
    candidates = list(extensions.glob("openai.chatgpt-*-win32-x64/bin/windows-x86_64/codex.exe"))
    if not candidates:
        raise QuotaError("The official Codex CLI could not be located.")
    return str(max(candidates, key=lambda p: p.stat().st_mtime))


def isolation_overrides() -> list[str]:
    # These process-local overrides never modify the user's persisted settings.
    return ["-c", "analytics.enabled=false", "-c", "mcp_servers={}",
            "-c", "apps={_default={enabled=false}}",
            "-c", "features.remote_control=false", "-c", "features.plugins=false",
            "-c", "features.remote_plugin=false"]


class StdioProtocol:
    def __init__(self, process: subprocess.Popen):
        self.process = process
        self.messages: queue.Queue = queue.Queue()
        self.next_id = 0
        self.reader = threading.Thread(target=self._read, daemon=True)
        self.reader.start()

    def _read(self) -> None:
        try:
            while True:
                line = self.process.stdout.readline(1024 * 1024 + 1)
                if not line:
                    self.messages.put(None)
                    return
                if len(line) > 1024 * 1024:
                    self.messages.put(False)
                    return
                self.messages.put(json.loads(line))
        except (OSError, ValueError):
            self.messages.put(False)

    def send(self, message: dict) -> None:
        try:
            self.process.stdin.write(json.dumps(message).encode("utf-8") + b"\n")
            self.process.stdin.flush()
        except (OSError, ValueError):
            raise QuotaError("Codex quota connection closed unexpectedly.") from None

    def request(self, method: str, params: object, deadline: float) -> object:
        self.next_id += 1
        request_id = self.next_id
        self.send({"id": request_id, "method": method, "params": params})
        while True:
            if time.monotonic() >= deadline:
                raise QuotaError("Codex quota read timed out; allowance is unknown.")
            try:
                message = self.messages.get(timeout=max(0, deadline - time.monotonic()))
            except queue.Empty:
                raise QuotaError("Codex quota read timed out; allowance is unknown.") from None
            if not isinstance(message, dict):
                raise QuotaError("Codex quota connection returned invalid data or closed.")
            if "method" in message:
                if "id" in message:
                    # Never authorize tools, login, or any other server-initiated work.
                    self.send({"id": message["id"], "error": {
                        "code": -32601, "message": "Read-only quota client does not support requests"
                    }})
                continue
            if message.get("id") != request_id:
                continue
            if "error" in message:
                raise QuotaError("Official Codex quota read failed; check account access in Codex.")
            if "result" not in message:
                raise QuotaError("Codex quota response is incomplete.")
            return message["result"]


def run_codex(timeout: float = 30.0) -> dict:
    executable = find_codex()
    args = [executable, *isolation_overrides(), "app-server", "--listen", "stdio://"]
    # A new empty directory prevents project-local settings and AGENTS context.
    # Authentication stays owned by the official CLI in its existing home.
    with tempfile.TemporaryDirectory(prefix="codex-quota-") as workspace:
        process = subprocess.Popen(args, cwd=workspace, stdin=subprocess.PIPE,
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        try:
            protocol = StdioProtocol(process)
            deadline = time.monotonic() + timeout
            protocol.request("initialize", {"clientInfo": {
                "name": "codex_quota_monitor", "version": "1.0.0"
            }, "capabilities": {"experimentalApi": False}}, deadline)
            protocol.send({"method": "initialized", "params": {}})
            result = protocol.request("account/rateLimits/read", None, deadline)
            return parse_rate_limits(result)
        finally:
            if process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=5)
            for stream in (process.stdin, process.stdout):
                if stream:
                    stream.close()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--timeout", type=float, default=30.0)
    args = parser.parse_args()
    try:
        if not 1 <= args.timeout <= 120:
            raise QuotaError("Quota read timeout must be between 1 and 120 seconds.")
        result = run_codex(args.timeout)
        print(json.dumps(result))
        return 0
    except (QuotaError, OSError, subprocess.SubprocessError) as error:
        # Never stringify arbitrary OS/process errors (paths or credentials).
        message = str(error) if isinstance(error, QuotaError) else "Codex quota monitor could not run."
        print(json.dumps({"provider": "codex", "status": "unknown", "windows": [], "error": message}))
        return 1


if __name__ == "__main__":
    sys.exit(main())
